### ISSUE TITLE
unicodeDecodeError 

### ISSUE THREAD

**Issue by melikaaz** [amigcamel/Jseg#1]
I want to use jieba Segmentator for chinese, but it is giving me this DecodeError :

>>> from jseg.jieba import Jieba
>>> j = Jieba()

DEBUG:jseg.jieba:loading default dictionary
Traceback (most recent call last):
  File "<pyshell#58>", line 1, in <module>
    j = Jieba()
  File "C:\Python34\jseg\jieba.py", line 89, in __init__
    self._gen_trie()
  File "C:\Python34\jseg\jieba.py", line 122, in _gen_trie
    dic = self._load_dic()
  File "C:\Python34\jseg\jieba.py", line 101, in _load_dic
    raw = tf.read()
  File "C:\Python34\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 44: character maps to <undefined>

**Comment by amigcamel** [comment]
Seems like an encoding problem.  
Please refer to the latest version of [Jseg](https://github.com/amigcamel/Jseg)
If the problem still occurs, please let me know

**Comment by gbonnycastle** [comment]
I've received identical UnicodeDecodeError with latest version of jseg 

>pip install jseg
...
Successfully installed jseg-0.0.2.1 six-1.11.0

>pip install -U jseg
Requirement already up-to-date: jseg in f:\program files (x86)\python35-32\lib\site-packages
Requirement already up-to-date: nltk==3.0.3 in f:\program files (x86)\python35-32\lib\site-packages (from jseg)
Requirement already up-to-date: six==1.11.0 in f:\program files (x86)\python35-32\lib\site-packages (from jseg)

**Comment by amigcamel** [comment]
@gbonnycastle I guess this happens on Windows only, and the bug has been fixed in [1491cff](https://github.com/amigcamel/Jseg/commit/1491cff391ff16c747a7f429ab66c9c442455b4b).  
Please do  `pip install -U jseg` to see if it works, thanks.
